import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./navbar";
import { BreadCrumbs } from "./components/bread-crumbs";
import { Footer } from "./Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className=" overflow-hidden">
          <div className="grid-border nav-padding">
            <Navbar />
          </div>

          {/* Page content */}
          <main>
            <div className=" nav-padding">
              <div className="px-5">
                <BreadCrumbs />
              </div>
            </div>
            {children}
          </main>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
